-- =====================================================================
-- Flyway Migration V74: Create Weather/Climate System Tables
-- =====================================================================
-- Description: Creates planetary_weather and all child tables for the
--              WeatherCreator system. Follows same pattern as
--              planetary_habitability and planetary_magnetic_field.
-- Author: Chase
-- Date: 2026-02-12
-- =====================================================================

-- =====================================================================
-- MAIN WEATHER TABLE (1:1 with planet, optional 1:1 with moon)
-- =====================================================================
CREATE TABLE ud.planetary_weather (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planet_id BIGINT,
    moon_id BIGINT,

    -- Atmospheric Structure
    scale_height_km DOUBLE PRECISION,
    tropopause_altitude_km DOUBLE PRECISION,
    total_atmosphere_height_km DOUBLE PRECISION,
    sky_color VARCHAR(50),
    sky_color_description VARCHAR(200),
    twilight_duration_minutes DOUBLE PRECISION,

    -- Temperature & Climate
    day_night_temp_range_k DOUBLE PRECISION,
    seasonal_temp_amplitude_k DOUBLE PRECISION,
    season_description VARCHAR(300),
    thermal_inertia_class VARCHAR(30),
    mean_equatorial_temp_k DOUBLE PRECISION,
    mean_polar_temp_k DOUBLE PRECISION,

    -- Wind & Circulation
    circulation_pattern VARCHAR(50),
    circulation_cell_count INTEGER,
    jet_stream_count INTEGER,
    jet_stream_speed_ms DOUBLE PRECISION,
    mean_surface_wind_speed_ms DOUBLE PRECISION,
    max_gust_speed_ms DOUBLE PRECISION,
    wind_intensity VARCHAR(30),
    has_super_rotation BOOLEAN DEFAULT FALSE,
    super_rotation_factor DOUBLE PRECISION,

    -- Clouds
    cloud_coverage_percent DOUBLE PRECISION,
    cloud_coverage_class VARCHAR(30),
    primary_cloud_composition VARCHAR(100),

    -- Precipitation
    has_precipitation BOOLEAN DEFAULT FALSE,
    primary_precipitation_type VARCHAR(50),
    precipitation_frequency VARCHAR(30),
    precipitation_reaches_surface BOOLEAN DEFAULT TRUE,

    -- Storms
    storm_frequency VARCHAR(30),
    typical_storm_wind_speed_ms DOUBLE PRECISION,
    has_dust_storms BOOLEAN DEFAULT FALSE,
    dust_storms_can_be_global BOOLEAN DEFAULT FALSE,
    has_lightning BOOLEAN DEFAULT FALSE,
    lightning_type VARCHAR(50),

    -- Tidal Effects
    tidal_range_meters DOUBLE PRECISION,
    dominant_tidal_period_hours DOUBLE PRECISION,
    atmospheric_tidal_effect VARCHAR(200),

    -- Gas Giant Specific
    number_of_bands INTEGER,
    internal_heat_flux_wm2 DOUBLE PRECISION,
    internal_to_stellar_ratio DOUBLE PRECISION,
    has_great_dark_spot BOOLEAN DEFAULT FALSE,

    -- Visual / Narrative
    daytime_sky_description VARCHAR(500),
    nighttime_sky_description VARCHAR(500),
    sunset_description VARCHAR(300),
    outdoor_exposure_rating VARCHAR(50),
    survival_time_description VARCHAR(200),

    -- Weather Summary
    weather_summary VARCHAR(1000),
    weather_severity VARCHAR(30),

    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT chk_weather_scale_height_positive CHECK (scale_height_km IS NULL OR scale_height_km > 0),
    CONSTRAINT chk_weather_cloud_coverage_range CHECK (cloud_coverage_percent IS NULL OR (cloud_coverage_percent >= 0 AND cloud_coverage_percent <= 100)),
    CONSTRAINT chk_weather_day_night_range_positive CHECK (day_night_temp_range_k IS NULL OR day_night_temp_range_k >= 0),
    CONSTRAINT chk_weather_seasonal_amp_positive CHECK (seasonal_temp_amplitude_k IS NULL OR seasonal_temp_amplitude_k >= 0),
    CONSTRAINT chk_weather_wind_speed_positive CHECK (mean_surface_wind_speed_ms IS NULL OR mean_surface_wind_speed_ms >= 0),
    CONSTRAINT chk_weather_tidal_range_positive CHECK (tidal_range_meters IS NULL OR tidal_range_meters >= 0)
);

ALTER TABLE ud.planetary_weather OWNER TO starcreator_dev;

COMMENT ON TABLE ud.planetary_weather IS 'Weather and climate assessment for planets and moons with atmospheres. Calculated post-generation from orbital, atmospheric, and geological data.';
COMMENT ON COLUMN ud.planetary_weather.planet_id IS 'FK to planet. Mutually exclusive with moon_id.';
COMMENT ON COLUMN ud.planetary_weather.moon_id IS 'FK to moon. Mutually exclusive with planet_id.';
COMMENT ON COLUMN ud.planetary_weather.scale_height_km IS 'Atmospheric scale height H = kT/(μg) in km. Earth ~8.5, Titan ~21, Jupiter ~27.';
COMMENT ON COLUMN ud.planetary_weather.tropopause_altitude_km IS 'Altitude of tropopause boundary where lapse rate reverses.';
COMMENT ON COLUMN ud.planetary_weather.sky_color IS 'Dominant sky color enum: BLUE, DEEP_BLUE, PALE_BLUE, ORANGE, BUTTERSCOTCH, TEAL, PINK, SALMON, WHITE, BLACK, YELLOW, GREEN, RED';
COMMENT ON COLUMN ud.planetary_weather.twilight_duration_minutes IS 'Duration of twilight transition. Dense atmospheres = long, thin = short.';
COMMENT ON COLUMN ud.planetary_weather.circulation_pattern IS 'Global circulation: SINGLE_HADLEY, THREE_CELL, MULTI_BANDED, TIDALLY_LOCKED_SUBSTELLAR, SUPER_ROTATING, MINIMAL';
COMMENT ON COLUMN ud.planetary_weather.wind_intensity IS 'Surface wind classification: CALM, LIGHT, MODERATE, STRONG, EXTREME, HURRICANE';
COMMENT ON COLUMN ud.planetary_weather.cloud_coverage_class IS 'Cloud coverage: CLEAR, SCATTERED, BROKEN, OVERCAST, OPAQUE_DECK';
COMMENT ON COLUMN ud.planetary_weather.precipitation_frequency IS 'How often precipitation occurs: NEVER, RARE, OCCASIONAL, FREQUENT, CONTINUOUS';
COMMENT ON COLUMN ud.planetary_weather.storm_frequency IS 'Storm system frequency: RARE, OCCASIONAL, FREQUENT, CONSTANT';
COMMENT ON COLUMN ud.planetary_weather.outdoor_exposure_rating IS 'Human survival: SHIRT_SLEEVE, COLD_WEATHER_GEAR, ASSISTED, PRESSURE_SUIT, LETHAL_MINUTES, LETHAL_SECONDS, INSTANT_DEATH';
COMMENT ON COLUMN ud.planetary_weather.weather_severity IS 'Overall weather severity: BENIGN, MILD, MODERATE, SEVERE, EXTREME, APOCALYPTIC';
COMMENT ON COLUMN ud.planetary_weather.thermal_inertia_class IS 'How quickly surface responds to heating: LOW, MODERATE, HIGH, EXTREME';
COMMENT ON COLUMN ud.planetary_weather.internal_to_stellar_ratio IS 'Gas giants: ratio of internal heat to received stellar flux. Jupiter ~1.67.';

-- Unique partial indexes (same pattern as magnetic field)
CREATE UNIQUE INDEX idx_weather_planet_id_unique ON ud.planetary_weather(planet_id) WHERE planet_id IS NOT NULL;
CREATE UNIQUE INDEX idx_weather_moon_id_unique ON ud.planetary_weather(moon_id) WHERE moon_id IS NOT NULL;
CREATE INDEX idx_weather_planet_id ON ud.planetary_weather(planet_id);
CREATE INDEX idx_weather_moon_id ON ud.planetary_weather(moon_id);
CREATE INDEX idx_weather_severity ON ud.planetary_weather(weather_severity);

-- Foreign keys
ALTER TABLE ud.planetary_weather
    ADD CONSTRAINT fk_weather_planet FOREIGN KEY (planet_id) REFERENCES ud.planet(id) ON DELETE CASCADE;
ALTER TABLE ud.planetary_weather
    ADD CONSTRAINT fk_weather_moon FOREIGN KEY (moon_id) REFERENCES ud.moon(id) ON DELETE CASCADE;

-- =====================================================================
-- CLIMATE ZONES (1:many with planetary_weather)
-- =====================================================================
CREATE TABLE ud.climate_zone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weather_id BIGINT NOT NULL,
    zone_name VARCHAR(50) NOT NULL,
    latitude_start_degrees DOUBLE PRECISION,
    latitude_end_degrees DOUBLE PRECISION,
    coverage_percent DOUBLE PRECISION,
    mean_temp_k DOUBLE PRECISION,
    description VARCHAR(300),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_cz_coverage_range CHECK (coverage_percent IS NULL OR (coverage_percent >= 0 AND coverage_percent <= 100)),
    CONSTRAINT chk_cz_lat_range CHECK (
        (latitude_start_degrees IS NULL OR (latitude_start_degrees >= -90 AND latitude_start_degrees <= 90))
        AND (latitude_end_degrees IS NULL OR (latitude_end_degrees >= -90 AND latitude_end_degrees <= 90))
    )
);

ALTER TABLE ud.climate_zone OWNER TO starcreator_dev;
COMMENT ON TABLE ud.climate_zone IS 'Climate zone distribution for a planet. Zones: TROPICAL, TEMPERATE, POLAR, SUBSTELLAR, TWILIGHT, ANTISTELLAR, EQUATORIAL_BAND, etc.';

ALTER TABLE ud.climate_zone
    ADD CONSTRAINT fk_cz_weather FOREIGN KEY (weather_id) REFERENCES ud.planetary_weather(id) ON DELETE CASCADE;
CREATE INDEX idx_cz_weather_id ON ud.climate_zone(weather_id);

-- =====================================================================
-- CLOUD LAYERS (1:many with planetary_weather)
-- =====================================================================
CREATE TABLE ud.cloud_layer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weather_id BIGINT NOT NULL,
    layer_order INTEGER NOT NULL,
    composition VARCHAR(100) NOT NULL,
    altitude_km DOUBLE PRECISION,
    thickness_km DOUBLE PRECISION,
    temperature_k DOUBLE PRECISION,
    opacity VARCHAR(30),
    color VARCHAR(50),
    description VARCHAR(200),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_cl_altitude_positive CHECK (altitude_km IS NULL OR altitude_km >= 0),
    CONSTRAINT chk_cl_thickness_positive CHECK (thickness_km IS NULL OR thickness_km > 0)
);

ALTER TABLE ud.cloud_layer OWNER TO starcreator_dev;
COMMENT ON TABLE ud.cloud_layer IS 'Individual cloud layers ordered from surface upward. Composition: H2O, NH3, NH4SH, CH4, H2SO4, CO2_ICE, HYDROCARBON_HAZE, SILICATE, IRON';
COMMENT ON COLUMN ud.cloud_layer.opacity IS 'Layer opacity: TRANSPARENT, THIN, MODERATE, THICK, OPAQUE';

ALTER TABLE ud.cloud_layer
    ADD CONSTRAINT fk_cl_weather FOREIGN KEY (weather_id) REFERENCES ud.planetary_weather(id) ON DELETE CASCADE;
CREATE INDEX idx_cl_weather_id ON ud.cloud_layer(weather_id);

-- =====================================================================
-- PRECIPITATION TYPES (1:many with planetary_weather)
-- =====================================================================
CREATE TABLE ud.precipitation_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weather_id BIGINT NOT NULL,
    substance VARCHAR(50) NOT NULL,
    phase VARCHAR(30) NOT NULL,
    frequency VARCHAR(30),
    intensity VARCHAR(30),
    reaches_surface BOOLEAN DEFAULT TRUE,
    description VARCHAR(200),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ud.precipitation_type OWNER TO starcreator_dev;
COMMENT ON TABLE ud.precipitation_type IS 'Precipitation types for a planet. Substance: WATER, METHANE, AMMONIA, SULFURIC_ACID, CO2, IRON, DIAMOND, HYDROCARBON. Phase: RAIN, SNOW, HAIL, SLEET, DRIZZLE, VIRGA';

ALTER TABLE ud.precipitation_type
    ADD CONSTRAINT fk_pt_weather FOREIGN KEY (weather_id) REFERENCES ud.planetary_weather(id) ON DELETE CASCADE;
CREATE INDEX idx_pt_weather_id ON ud.precipitation_type(weather_id);

-- =====================================================================
-- EXTREME WEATHER EVENTS (1:many with planetary_weather)
-- =====================================================================
CREATE TABLE ud.extreme_weather_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weather_id BIGINT NOT NULL,
    event_name VARCHAR(100) NOT NULL,
    event_type VARCHAR(50),
    severity VARCHAR(30),
    frequency VARCHAR(30),
    description VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ud.extreme_weather_event OWNER TO starcreator_dev;
COMMENT ON TABLE ud.extreme_weather_event IS 'Extreme weather phenomena. Types: DUST_STORM, HYPERCANE, GREAT_VORTEX, MONSOON, SUPERSTORM, GLOBAL_DUST, LIGHTNING_STORM, METHANE_MONSOON, ACID_RAIN_CYCLE';
COMMENT ON COLUMN ud.extreme_weather_event.severity IS 'Event severity: LOW, MODERATE, HIGH, EXTREME, CATASTROPHIC';
COMMENT ON COLUMN ud.extreme_weather_event.frequency IS 'Event frequency: CONSTANT, FREQUENT, SEASONAL, OCCASIONAL, RARE, ONCE_PER_CENTURY';

ALTER TABLE ud.extreme_weather_event
    ADD CONSTRAINT fk_ewe_weather FOREIGN KEY (weather_id) REFERENCES ud.planetary_weather(id) ON DELETE CASCADE;
CREATE INDEX idx_ewe_weather_id ON ud.extreme_weather_event(weather_id);

-- =====================================================================
-- MOON SKY APPEARANCE (1:many with planetary_weather)
-- =====================================================================
CREATE TABLE ud.moon_sky_appearance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weather_id BIGINT NOT NULL,
    moon_id BIGINT NOT NULL,
    angular_diameter_degrees DOUBLE PRECISION,
    phase_cycle_days DOUBLE PRECISION,
    brightness_relative_to_full_moon DOUBLE PRECISION,
    is_visible_in_daytime BOOLEAN DEFAULT FALSE,
    apparent_color VARCHAR(50),
    description VARCHAR(200),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_msa_angular_positive CHECK (angular_diameter_degrees IS NULL OR angular_diameter_degrees > 0)
);

ALTER TABLE ud.moon_sky_appearance OWNER TO starcreator_dev;
COMMENT ON TABLE ud.moon_sky_appearance IS 'How each moon appears from the planet surface. Angular size, brightness, phase cycle for world-building narrative.';

ALTER TABLE ud.moon_sky_appearance
    ADD CONSTRAINT fk_msa_weather FOREIGN KEY (weather_id) REFERENCES ud.planetary_weather(id) ON DELETE CASCADE;
ALTER TABLE ud.moon_sky_appearance
    ADD CONSTRAINT fk_msa_moon FOREIGN KEY (moon_id) REFERENCES ud.moon(id) ON DELETE CASCADE;
CREATE INDEX idx_msa_weather_id ON ud.moon_sky_appearance(weather_id);

-- =====================================================================
-- ECLIPSE DATA (1:many with planetary_weather)
-- =====================================================================
CREATE TABLE ud.eclipse_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weather_id BIGINT NOT NULL,
    eclipse_source VARCHAR(50),
    source_body_name VARCHAR(100),
    eclipse_type VARCHAR(30),
    frequency_per_year DOUBLE PRECISION,
    typical_duration_minutes DOUBLE PRECISION,
    description VARCHAR(300),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ud.eclipse_data OWNER TO starcreator_dev;
COMMENT ON TABLE ud.eclipse_data IS 'Eclipse events visible from planet. Source: MOON_SOLAR, MOON_LUNAR, BINARY_STAR. Type: TOTAL, PARTIAL, ANNULAR, TRANSIT';

ALTER TABLE ud.eclipse_data
    ADD CONSTRAINT fk_ed_weather FOREIGN KEY (weather_id) REFERENCES ud.planetary_weather(id) ON DELETE CASCADE;
CREATE INDEX idx_ed_weather_id ON ud.eclipse_data(weather_id);

-- =====================================================================
-- WEATHER HAZARDS (1:many with planetary_weather)
-- =====================================================================
CREATE TABLE ud.weather_hazard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weather_id BIGINT NOT NULL,
    hazard_name VARCHAR(100) NOT NULL,
    hazard_type VARCHAR(50),
    severity VARCHAR(30),
    frequency VARCHAR(30),
    description VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ud.weather_hazard OWNER TO starcreator_dev;
COMMENT ON TABLE ud.weather_hazard IS 'Weather-related hazards for scout reports. Types: THERMAL, WIND, STORM, RADIATION, CHEMICAL, PRESSURE, ELECTRICAL';
COMMENT ON COLUMN ud.weather_hazard.severity IS 'Hazard severity: LOW, MODERATE, HIGH, EXTREME, LETHAL';

ALTER TABLE ud.weather_hazard
    ADD CONSTRAINT fk_wh_weather FOREIGN KEY (weather_id) REFERENCES ud.planetary_weather(id) ON DELETE CASCADE;
CREATE INDEX idx_wh_weather_id ON ud.weather_hazard(weather_id);

-- =====================================================================
-- REFERENCE TABLE: Cloud Composition Templates
-- =====================================================================
CREATE TABLE ref.cloud_composition_template (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atmosphere_classification VARCHAR(50) NOT NULL,
    substance VARCHAR(50) NOT NULL,
    min_temperature_k DOUBLE PRECISION,
    max_temperature_k DOUBLE PRECISION,
    typical_altitude_scale_heights DOUBLE PRECISION,
    opacity VARCHAR(30),
    color VARCHAR(50),
    description VARCHAR(200),
    weight INTEGER DEFAULT 100,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ref.cloud_composition_template OWNER TO starcreator_dev;
COMMENT ON TABLE ref.cloud_composition_template IS 'Reference data for cloud layer generation by atmosphere type and temperature range.';

-- Seed cloud composition templates
INSERT INTO ref.cloud_composition_template (atmosphere_classification, substance, min_temperature_k, max_temperature_k, typical_altitude_scale_heights, opacity, color, description, weight) VALUES
    -- Earth-like
    ('EARTH_LIKE', 'H2O', 200, 373, 1.0, 'MODERATE', 'White', 'Water vapor clouds — cumulus, stratus, cirrus', 200),
    ('EARTH_LIKE', 'H2O_ICE', 180, 240, 2.0, 'THIN', 'White', 'High-altitude ice crystal cirrus clouds', 150),
    -- Venus-like
    ('VENUS_LIKE', 'H2SO4', 320, 800, 1.5, 'OPAQUE', 'Yellow-White', 'Sulfuric acid cloud deck', 200),
    ('VENUS_LIKE', 'H2SO4', 400, 700, 1.0, 'THICK', 'Yellow', 'Lower sulfuric acid haze layer', 150),
    -- Mars-like
    ('MARS_LIKE', 'CO2_ICE', 130, 200, 1.5, 'THIN', 'White', 'CO2 ice crystal clouds at altitude', 150),
    ('MARS_LIKE', 'H2O_ICE', 170, 230, 1.0, 'THIN', 'White', 'Thin water ice cirrus clouds', 120),
    ('MARS_LIKE', 'DUST', 150, 400, 0.5, 'MODERATE', 'Salmon-Pink', 'Suspended dust haze', 180),
    -- Titan-like
    ('TITAN_LIKE', 'CH4', 60, 95, 0.5, 'MODERATE', 'Orange-Brown', 'Methane rain clouds', 180),
    ('TITAN_LIKE', 'HYDROCARBON_HAZE', 70, 200, 2.0, 'THICK', 'Orange', 'Photochemical hydrocarbon haze layers', 200),
    ('TITAN_LIKE', 'C2H6', 70, 110, 0.8, 'THIN', 'Brown', 'Ethane condensation clouds', 100),
    -- Jovian
    ('JOVIAN', 'NH3', 110, 160, 1.0, 'THICK', 'White', 'Ammonia ice crystal clouds — visible top layer', 200),
    ('JOVIAN', 'NH4SH', 180, 270, 0.5, 'THICK', 'Brown-Red', 'Ammonium hydrosulfide clouds — gives brown/red banding', 180),
    ('JOVIAN', 'H2O', 250, 350, 0.3, 'THICK', 'White-Grey', 'Deep water clouds below visible deck', 150),
    -- Ice Giant
    ('ICE_GIANT', 'CH4', 50, 90, 1.5, 'MODERATE', 'Cyan-Blue', 'Methane ice clouds — absorb red light', 200),
    ('ICE_GIANT', 'H2S', 100, 200, 0.8, 'THIN', 'Pale Yellow', 'Hydrogen sulfide haze layer', 120),
    ('ICE_GIANT', 'NH3', 100, 160, 0.5, 'MODERATE', 'White', 'Ammonia clouds at depth', 150),
    -- Volcanic
    ('VOLCANIC', 'SO2', 200, 600, 1.0, 'MODERATE', 'Yellow-Grey', 'Sulfur dioxide volcanic clouds', 180),
    ('VOLCANIC', 'SULFUR', 350, 800, 0.5, 'THIN', 'Yellow', 'Elemental sulfur aerosol haze', 120),
    -- Ammonia
    ('AMMONIA', 'NH3', 100, 250, 1.0, 'THICK', 'White', 'Ammonia ice and liquid clouds', 200),
    ('AMMONIA', 'NH3_LIQUID', 200, 300, 0.5, 'MODERATE', 'Pale Blue', 'Liquid ammonia droplet clouds', 120),
    -- Reducing
    ('REDUCING', 'HYDROCARBON_HAZE', 100, 400, 2.0, 'MODERATE', 'Brown-Orange', 'Photochemical haze from H2/CH4', 150),
    -- Corrosive
    ('CORROSIVE', 'HCL', 200, 500, 1.0, 'MODERATE', 'Pale Green', 'Hydrochloric acid aerosol clouds', 150),
    ('CORROSIVE', 'HF', 250, 500, 1.0, 'THIN', 'Colorless-White', 'Hydrofluoric acid mist', 100),
    -- Exotic
    ('EXOTIC', 'SILICATE', 1500, 3000, 0.5, 'THICK', 'Red-Orange', 'Silicate rock vapor clouds on ultrahot worlds', 150),
    ('EXOTIC', 'IRON', 1800, 3000, 0.5, 'MODERATE', 'Dark Grey', 'Iron vapor condensation clouds', 120),
    ('EXOTIC', 'CORUNDUM', 1600, 2800, 0.8, 'MODERATE', 'Ruby Red', 'Aluminum oxide crystal clouds', 80);

-- =====================================================================
-- REFERENCE TABLE: Sky Color Templates
-- =====================================================================
CREATE TABLE ref.sky_color_template (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atmosphere_classification VARCHAR(50),
    dominant_gas VARCHAR(20),
    pressure_min_bar DOUBLE PRECISION,
    pressure_max_bar DOUBLE PRECISION,
    sky_color VARCHAR(50) NOT NULL,
    description VARCHAR(200),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ref.sky_color_template OWNER TO starcreator_dev;
COMMENT ON TABLE ref.sky_color_template IS 'Reference data for sky color determination from atmosphere composition and pressure.';

INSERT INTO ref.sky_color_template (atmosphere_classification, dominant_gas, pressure_min_bar, pressure_max_bar, sky_color, description) VALUES
    ('EARTH_LIKE', 'N2', 0.5, 3.0, 'BLUE', 'Rayleigh scattering in N2/O2 atmosphere produces blue sky'),
    ('EARTH_LIKE', 'N2', 3.0, 10.0, 'DEEP_BLUE', 'Dense N2/O2 atmosphere deepens blue color'),
    ('VENUS_LIKE', 'CO2', 10.0, 200.0, 'ORANGE', 'Dense CO2 scatters longer wavelengths, yellow-orange sky'),
    ('MARS_LIKE', 'CO2', 0.001, 0.02, 'BUTTERSCOTCH', 'Thin CO2 with suspended dust creates butterscotch/salmon sky'),
    ('MARS_LIKE', 'CO2', 0.0, 0.001, 'NEAR_BLACK', 'Near-vacuum CO2 — stars visible in daytime, dark sky'),
    ('TITAN_LIKE', 'N2', 0.5, 5.0, 'ORANGE', 'Nitrogen with hydrocarbon haze creates deep orange sky'),
    ('JOVIAN', 'H2', 0.1, 10000.0, 'PALE_BLUE', 'Hydrogen Rayleigh scattering at cloud tops'),
    ('ICE_GIANT', 'H2', 0.1, 10000.0, 'CYAN', 'H2 scattering plus methane red absorption creates cyan/teal'),
    ('VOLCANIC', 'SO2', 0.001, 10.0, 'YELLOW_GREY', 'SO2 and sulfur aerosols create hazy yellow-grey sky'),
    ('AMMONIA', 'NH3', 0.5, 5.0, 'PALE_YELLOW', 'Ammonia atmosphere with whitish-yellow sky'),
    ('REDUCING', 'H2', 0.5, 5.0, 'BROWN_ORANGE', 'Hydrogen with photochemical haze creates brownish sky'),
    ('CORROSIVE', 'CL2', 0.5, 5.0, 'GREEN', 'Chlorine gas absorption produces greenish sky'),
    ('EXOTIC', NULL, 0.1, 100.0, 'RED_ORANGE', 'Metallic vapor scattering on ultrahot worlds'),
    (NULL, NULL, 0.0, 0.0001, 'BLACK', 'Near-vacuum — essentially no sky, stars always visible');

-- =====================================================================
-- REFERENCE TABLE: Precipitation Templates
-- =====================================================================
CREATE TABLE ref.precipitation_template (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cloud_substance VARCHAR(50) NOT NULL,
    surface_temp_min_k DOUBLE PRECISION,
    surface_temp_max_k DOUBLE PRECISION,
    phase VARCHAR(30) NOT NULL,
    reaches_surface BOOLEAN DEFAULT TRUE,
    description VARCHAR(200),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ref.precipitation_template OWNER TO starcreator_dev;
COMMENT ON TABLE ref.precipitation_template IS 'Maps cloud substance + surface temperature to precipitation type and phase.';

INSERT INTO ref.precipitation_template (cloud_substance, surface_temp_min_k, surface_temp_max_k, phase, reaches_surface, description) VALUES
    ('H2O', 273, 500, 'RAIN', TRUE, 'Liquid water rain'),
    ('H2O', 200, 273, 'SNOW', TRUE, 'Water ice snow and frost'),
    ('H2O', 250, 320, 'HAIL', TRUE, 'Ice pellets from strong convective updrafts'),
    ('H2O_ICE', 150, 250, 'SNOW', TRUE, 'High-altitude ice crystal precipitation'),
    ('CH4', 80, 95, 'RAIN', TRUE, 'Liquid methane rain — Titan-like'),
    ('CH4', 60, 80, 'SNOW', TRUE, 'Methane ice crystal precipitation'),
    ('NH3', 195, 240, 'RAIN', TRUE, 'Liquid ammonia rain'),
    ('NH3', 130, 195, 'SNOW', TRUE, 'Ammonia ice crystal snow'),
    ('H2SO4', 300, 500, 'VIRGA', FALSE, 'Sulfuric acid rain that evaporates before reaching surface'),
    ('H2SO4', 200, 300, 'DRIZZLE', TRUE, 'Dilute sulfuric acid drizzle at lower temperatures'),
    ('CO2_ICE', 130, 200, 'SNOW', TRUE, 'Dry ice snowfall — CO2 condensation'),
    ('SO2', 200, 400, 'RAIN', TRUE, 'Sulfur dioxide condensation rain'),
    ('IRON', 1500, 2500, 'RAIN', TRUE, 'Molten iron rain on ultrahot worlds'),
    ('SILICATE', 1800, 3000, 'RAIN', TRUE, 'Liquid rock rain on ultrahot gas giants'),
    ('HYDROCARBON_HAZE', 70, 200, 'DRIZZLE', TRUE, 'Hydrocarbon tar drizzle from photochemical haze');
